patch-tech/dpm

- src/command.rs
Checks whether the directory `out_dir` is the default `dist`. If so, create the default directory to put packages in.
Test plan:
- ran `cargo run build-package --package-identifier test-package@0.1.0 python` and checked contents in dist directory
> fix(pat-3987): create dist directory when no -o

- src/command/snowflake.rs
Increase max message decoding size for gRPC client to 32 MB.
1. [Before fix] Described a source without any table or schema filters to trigger error:
```
connected to https://agent.dpm.sh/
introspecting ...
thread 'main' panicked at 'error during `ExecuteQuery`: 
Status { 
code: OutOfRange, 
message: "Error, message length too large: found 4430148 bytes, the limit is: 4194304 bytes", 
metadata: MetadataMap { headers: {"date": "Fri, 18 Aug 2023 23:04:37 GMT", "content-type": "application/grpc", "grpc-accept-encoding": "identity, deflate, gzip", "strict-transport-security": "max-age=15724800; includeSubDomains"} }, source: None }',
/Users/ajith/Code/dpm/src/command/snowflake.rs:176:19
```
1. [After fix] The command runs successfully:
```
connected to https://agent.dpm.sh/
introspecting ... …
```
> fix(pat-3906): increase max message decoding size to 32MB

- CHANGELOG.md
- DEVELOPMENT.md
- Set up the changelog for easy creation of entries
- Document process
No change to Cargo.toml was needed as `0.1.0` has been the version since inception.
> Release v0.1.0

- src/command.rs
- src/command/source.rs
dpm help text:
```
Create data packages: libraries tailored to access versioned datasets
Usage: dpm <COMMAND>
Commands:
describe       Create a data package descriptor that describes some source's data
build-package  Build a data package from a data package descriptor
login          Log into DPM Cloud
publish        Create a data package in DPM Cloud
source         Create and list data sources
update         Update a data package to a new version
completions    Write the tab completion file for a shell
help           Print this message or the help of the given subcommand(s)
Options:
-h, --help     Print help
-V, --version  Print version
```
source help text:
```
Create and list data sources
Usage: dpm source <COMMAND>
Commands:
create  Create a new source
list    List sources available to …
```
> improve(pat-4032): add source and update helptext

- src/command/login.rs
when `dpm login` is run, dpm now checks for the existance of the `session.json` path before running login steps.
Test Plan:
1. Removed `session.json` to reset login, then ran the `dpm login` step.
2. Ran the dpm login step again, which outputted:
```
Session file present at: /Users/gunner/Library/Application Support/tech.patch.dpm/session.json
You are already logged in
```
> feat(pat-4033): make login idempotent

- src/codegen.rs
- src/codegen/csharp.rs
- static/csharp/Dpm/BooleanFieldExpr.cs
- static/csharp/Dpm/DatasetClient.cs
- static/csharp/Dpm/Dpm.csproj
- static/csharp/Dpm/Field.cs
- static/csharp/Dpm/FieldExpr.cs
- static/csharp/Dpm/Operator.cs
- static/csharp/Dpm/Scalar.cs
- static/csharp/Dpm/Table.cs
- static/csharp/Dpm/UnaryBooleanFieldExpr.cs
- Enables codegen for target `Csharp` .
- Adds static C# code for field expression, and skeleton code for a few derived classes, and `Table`.
- Generated C# codegen that can be built with `dotnet`.
- TBD in subsequent PRs:
> feat(pat-4053): c# codegen, field expr class, skeletons for Field, Table classes'

- static/csharp/Dpm/DpmAgentClient.cs
- static/csharp/Dpm/Table.cs
- Adds a `dpm-agent` client to `Table` to enable compiling and executing queries on the source.
1. Generated C# target code from data package descriptor: 
```bash
cargo run build-package -p "Snowflake Demo Package (fast)@0.1.0" -o ~/Sandbox/data-pkgs/rusty/ -y csharp
```
2. Built and installed `dotnet nuget` package. In the target output directory:
```bash
dot pack SnowflakeDemoPackageFast.sln
```
> ```bash
>    MSBuild version 17.6.10+2679cf5a9 for .NET
>    Determining projects to restore...
>    All projects are up-to-date for restore.
>    SnowflakeDemoPackageFast -> /Users/ajith/Sandbox/data- 
>    pkgs/rusty/csharp/SnowflakeDemoPackageFast@0.1.0.0.1.0/SnowflakeDemoPackageFast/bin/Debug/net6.0/SnowflakeDemoPackageFast.dll
> …
```
> feat(pat-4053): enables compiling and executing query

- CHANGELOG.md
- static/csharp/Dpm/Field.cs
- static/csharp/Dpm/LiteralField.cs
- static/csharp/DpmTest/UnitTest1.cs
- static/nodejs/src/backends/dpm_agent/dpm_agent_client.ts
- static/nodejs/src/field.ts
- static/nodejs/src/field_expr.ts
- static/nodejs/test/field.test.ts
- static/python/src/backends/dpm_agent/dpm_agent_client.py
- static/python/src/field.py
- static/python/src/field_expr.py
- static/python/src/test/field_test.py
- Support `sum` aggregator.
- Updated unit tests.
- Ran a query that includes `sum` via `dpm-agent` for each target.
- C#
```bash
ajith@ajiths-mbp  ~/Sandbox/gen-patchage/ts/testbed/UsImports/csharp  dotnet run
Discovering DPM Auth Token from session data.
compiled query = factsAppEngagementQuery(filter: { and: [{ age: { lt: 50 } },
{ appname: { like: "%walmart%" } }] }, orderBy: 
[{screenondurationMax: desc}], limit: 10) {
age
appname
totalScreenTime: screenondurationSum
screenDurationMax: screenondurationMax
}
Results =
Result { age = 21, appname = com.walmart.android, 
totalScreenTime = 1757310343.0, screenDurationMax = 65988384 }
Result { age = 46, appname = com.walmart.android, 
totalScreenTime = 10797960489.0, screenDurationMax = 6.436366E+7 }
Result { age = 42, appname = …
```
> feat(pat-4058): support sum aggregator

- src/codegen/csharp.rs
- Add command to build dotnet nuget package.
- Built c# package and verified that the `.nupkg` was created:
`cargo run build-package -p "Snowflake Demo Package (fast)@0.1.0" -o ~/Sandbox/data-pkgs/rusty/ -y csharp`
- 
```bash
> ls -lh SnowflakeDemoPackageFast/bin/Debug/SnowflakeDemoPackageFast.1.0.0.nupkg
-rw-r--r--  1 ajith  staff    47K Sep 11 11:42 SnowflakeDemoPackageFast/bin/Debug/SnowflakeDemoPackageFast.1.0.0.nupkg
```
> feat(pat-4226): cmd to build c# nuget package

- src/codegen/csharp.rs
- tests/nodejs/package-lock.json
- Update C# root dir path to use correct version string format `{pkg-semver}-{code-semver}`
- Use `<Version>` tag in `.csproj`; `<ReleaseVersion>` does not work.
- Built C# package and verified that the correct path was used for the target, and the .csproj had the expected `<Version>` tag.
- Created the `.nupkg` and added it to a test project; verified that the `<PackageReference>` in the test `.csproj` had the expected semver.
> fix(pat-4301): c# version tag

- CHANGELOG.md
- src/command.rs
- Restore the ability to run `build-package` off of a descriptor
This ability was removed in https://github.com/patch-tech/dpm/pull/113, but that was a detriment to UX: it resulted in a design where one must run `dpm publish` in order to build a package. That was untenable since it took away the ability for a user to QA their data package prior to publishing.
Help output:
```
% cargo run -- build-package --help
Finished dev [unoptimized + debuginfo] target(s) in 0.30s
Running `target/debug/dpm build-package --help`
Build an instance of a data package.
There are two different ways to specify the package to build:
1. By default (or with -d/--descriptor <FILE>) a package descriptor file
on the filesystem is used to define the tables and fields accessible
by the package.
2. With -p/--package …
```
> feat(build-package): Accept descriptor OR reference to published package

- CHANGELOG.md
- src/api.rs
- src/codegen/csharp.rs
- src/codegen/nodejs.rs
- src/codegen/python.rs
- src/command.rs
- src/command/build_package.rs
- src/command/publish.rs
- src/command/update.rs
- src/descriptor/data_package.rs
- Move `build-package` handler to its own module
- Delete duplicate `read_data_package` implementations and move to a method on `DataPackage`
- Only create release versions if generating from a published version; create draft versions otherwise
There will be one PR to follow this one, updating the codegen to work with `Version`'s that have prerelease data on them. (NB(ajith): This is already completed in [PR 151](https://app.graphite.dev/github/pr/patch-tech/dpm/151/fix-pat-4301-c-version-tag))
> feat(build-package): Create draft versions when building from local descriptors

- src/codegen/csharp.rs
- src/codegen/nodejs.rs
- src/codegen/python.rs
- src/command/snowflake.rs
- Warn+omit ARRAY, OBJECT, and VARIANT-type columns during `dpm describe snowflake`, as no codegen targets support them.
- Prefer explicit patterns instead of wildcard arm in codegen mappings from universal type -> language type. This will make it harder to unintentionally not cover a pattern in codegen.
PAT-4356 is a specialized version of a broader issue: There exist some Snowflake types that can be `describe`'d but not code-gen'd, not only in some targets but in _any_ targets. After auditing, it turns out the problematic data types are the [semi-structured types](https://docs.snowflake.com/en/sql-reference/data-types-semistructured):
- ARRAY
- OBJECT
- VARIANT
We definitely intend to support these better, but we don't currently and the result when attempting to use them is poor: a …
> fix(describe): Omit Snowflake's ARRAY, OBJECT, and VARIANT types

- Cargo.lock
- tests/nodejs/package-lock.json
- Regenerate Node.js test package-lock.json (`rm -r node_modules package-lock.json && npm i ../resources/generated/nodejs/test-snowflake-0.1.0-0.2.0.tgz`)
- Upgrade chrono (direct) and rustls-webpki (transitive) deps
At a glance, the Dependabot alerts resolved by this PR aren't exploitable, so this is mostly cleanup.
> chore(deps): Resolve Dependabot alerts

- CHANGELOG.md
- src/command/login.rs
- src/github.rs
- During `dpm login`, if a session.json exists but its token fails basic validation, continue with normal login flow
This saves the user the trouble of having to `rm` their session.json file in case the token within is no longer valid.
Already having a valid session:
```
% cargo run -- login
Compiling dpm v0.3.0 (/Users/spencer/code/dpm)
Finished dev [unoptimized + debuginfo] target(s) in 4.57s
Running `target/debug/dpm login`
Session file present at: /Users/spencer/Library/Application Support/tech.patch.dpm/session.json
You are already logged in.
```
Having an invalid session:
```
% cargo run -- login
Finished dev [unoptimized + debuginfo] target(s) in 0.13s
Running `target/debug/dpm login`
Login code has been copied to clipboard. Or, copy it here: 6A1F-0ABE
Enter it at this URL: …
```
> feat(login): If stored token fails basic validation, do flow

- static/nodejs/src/field.ts
- static/nodejs/src/field_expr.ts
- static/nodejs/test/field.test.ts
- Defines the `inPast` relative time check as `(lower <= <field> <= upper)`, where `lower, upper` are time bounds computed w.r.t. current time.
> feat(pat-3355): define `inPast` using computed time bounds in nodeJS

- .github/workflows/test-dpm.yml
- rust-toolchain.toml
- src/command/snowflake.rs
- Add [toolchain file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file), which `rustup` honors
- Replace uses of unmaintained GitHub Action in workflow with direct `cargo ...` invocations
This does not contradict the `rust-version = "1.69.0"` in Cargo.toml as that denotes the package's _minimum_ supported Rust version.
This may drift from whatever shell.nix pulls in from nixpkgs, but I'm not sure how to pin packages on Nix.
> chore: Add rust-toolchain.toml

- src/api.rs
- src/codegen/csharp.rs
- src/codegen/nodejs.rs
- src/codegen/python.rs
- src/command/publish.rs
- Warn user if publishing a version that's not accelerated as the successor to a version that is
- Resolve TODO whose time has come
- Drop misleading word in error message
Output when the scenario triggers:
```
WARNING: Latest release version (0.1.10) is accelerated, but the version about to be published (0.1.11) is not.
How do you want to proceed?:
> Ignore descriptor, publish accelerated
Respect descriptor, publish unaccelerated
```
I can navigate between the choices with up/down arrow keys, select one with Enter, or abort with Escape:
```
WARNING: Latest release version (0.1.10) is accelerated, but the version about to be published (0.1.11) is not.
Publish cancelled
```
> feat(publish): Warn if decelerating a package

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- src/api.rs
- src/command/init.rs
- src/command/source.rs
- Support `source create bigquery`
Help output:
```
% cargo run -- source create bigquery --help
Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Running `target/debug/dpm source create bigquery --help`
Create a BigQuery source
Usage: dpm source create bigquery --name <NAME> --project-id <PROJECT_ID> --staging-project-id <STAGING_PROJECT_ID> --credentials-key <PATH>
Options:
-n, --name <NAME>
Name to give the created source
--project-id <PROJECT_ID>
ID of your Google Cloud project
--staging-project-id <STAGING_PROJECT_ID>
ID of the Google Cloud project which dpm will use to perform change data capture on tables in this source. This value is only used when there exist accelerated data packages that access data from this source
--credentials-key <PATH>
Path to a JSON file …
```
> feat(source create): Support BigQuery

- src/api.rs
- src/command/build_package.rs
- src/command/publish.rs
- In GET APIs that can return 404, return `Option` from those to signify the 404 Not Found case
- Handle ^ as warranted in each call site
> fix(publish): Support publishing w/o creating draft version first

- src/api.rs
- src/command/init.rs
- Remove excess fields from struct type
Before:
```
error listing sources: missing field `name` at line 1 column 8762
```
After:
```
...
{
"uuid": "8fe30bbf-6ed4-4823-b656-c273223517e6",
"name": "first-bq-source",
"source_parameters": {
"type": "bigquery",
"project_id": "<redacted>",
"staging_project_id": "<redacted>"
}
},
...
```
> fix(source list): Support listing BigQuery sources

- src/api.rs
- src/command/build_package.rs
- Forbid building an instance of a package unless it's completed its initial sync
On an accelerated version in state "Error syncing initial":
```
% cargo run -- build-package -p automatically-fast@0.1.6 nodejs
Finished dev [unoptimized + debuginfo] target(s) in 5.90s
Running `target/debug/dpm build-package -p 'automatically-fast@0.1.6' nodejs`
package build failed: The package you requested to build failed to complete its initial acceleration.
Error: An unknown error occurred
Because it would be potentially confusing for an instance of an "accelerated" package
version to execute its queries without acceleration, the build will abort now.
Resolve the error above, then try building again.
```
On an accelerated version in state "Syncing":
```
% cargo run -- build-package -p …
```
> feat(build-package): Forbid building accelerated packages that are still initializing

- static/nodejs/src/field.ts
- static/nodejs/test/field.test.ts
- static/python/src/field.py
- static/python/src/test/field_test.py
This change fixes a bug in the underflow and overflow checking logic when adding duration to a time.
The bug's triggered on the beginning or the end of a month because the code
used the current date by default to perform the time arithmetic, and checked if
the result's day of month was before or after the current day of month.
The correct check should compare the entire date (YYYY-MM-DD) value.
NB: No changes are required for C# codegen as that logic uses C#'s in-built wrap output variable that indicates if adding duration to a `TimeOnly` instance underflowed or overflowed.
- Failing unit tests (that ran on 10/31/2023) now pass.
> fix(pat-4793): overflow and underflow check when adding duration to time

- Cargo.lock
- Cargo.toml
- src/command/init.rs
- src/command/update.rs
- src/descriptor/data_package.rs
- src/descriptor/table_schema.rs
- src/env.rs
- tests/integration_test/nodejs.rs
- tests/integration_test/python.rs
- tests/integration_test/target_tester.rs
- Add `inquire` dep. We already depend on the similar crate, `dialoguer`, but `inquire` seems a little bit nicer to look at
- Move fn to TableSchemaField.field_name method
- Add interative table/PK specification flow
See demo here: https://asciinema.org/a/8SoLuyfJuUgPpMNBTYwEztDGz
> feat(init): Add interactive table/PK selection flow

- src/api.rs
- Present "Syncing" as `Heathy` in `dpm package list` output
To match the terminology in the web app.
@msquinn @whelanBoyd should any other states change, too?
> fix(package list): Show syncing state as 'Healthy'

- src/api.rs
- src/command/init.rs
- src/command/source.rs
- Require `dataset` during `dpm source create bigquery`
This ensures that source discovery can occur in a constant number of reqs to BigQuery. In other words: it's fast. If this proves inconvenient—if we get feedback "it's cumbersome to create a new source for every BigQuery dataset!"—then we can look into making `dataset` optional later.
> feat(source create): Require `dataset` for BigQuery sources

- src/command.rs
- src/command/publish.rs
- Fix formatting of output
The bullet points previously had a bunch of leading whitespace. This gets rid of that.
> style: Fix formatting of output, remove misleading docs

- .github/workflows/test-dpm.yml
Poetry `1.7.0` fails on `poetry install` in the `dpm` Python static dir. Using `package install --no-root` prevents installing the static package and only install dependencies.
- Upgraded local `poetry` to 1.7.0.
- Running `poetry install` in `dpm/static/python` replicates the failure.
- `poetry install --no-root` runs successfully.
> fix(pat-4840): do not install static python package in CI

- src/api.rs
- src/command/update.rs
- src/descriptor/data_package.rs
- `SourcePath`: add method `qualified_name`
- Add method to consume the new `GET /sources/{}/metadata` endpoint
See upstack PR.
> feat(api): Add method to consume metadata endpoint

- src/api.rs
- src/command/init.rs
- src/command/snowflake.rs
- During `init`, use the source-type-agnostic metadata endpoint
- Drop now-unused `SnowflakeAllowListItem::Schema` variant
Now the only consumer of `snowflake::describe` is `dpm update`.  That command will be updated, and the dead code deleted, in https://linear.app/patch-tech/issue/PAT-4574/update-dpm-update-for-packages-that-include-bigquery-tables.
Verified creating a datapackage.json for a BigQuery source using
```
cargo run -- init -p new-pkg second-bq-source
```
Also, induced a failure to exercise the error handling:
```
% cargo run -- init -p new-pkg second-bq-source
Compiling dpm v0.4.0 (/Users/spencer/code/dpm)
Finished dev [unoptimized + debuginfo] target(s) in 9.60s
Running `target/debug/dpm init -p new-pkg second-bq-source`
warning: omitting field "name": unrecognized dpm data …
```
> feat(init): Use metadata endpoint

- src/api.rs
- src/command/source.rs
- On `source create bigquery`, rename `--credentials-key` to `--service-account-key`
This is more descriptive, using actual GCP terminology.
> feat(source create bigquery): Change name of CLI option

- src/descriptor/data_package.rs
- src/descriptor/table_schema.rs
- Ensure that all field variants require `type` in their serialized form
This has dual benefit:
1. When writing dataset versions to the backend, it ensures that we always _write_ a `type` property on every field
2. When reading dataset versions from the backend, it loudly alerts us to any situation where someone created an invalid dataset, where `type` _wasn't_ defined for some fields
(2) isn't theoretical. An earlier revision of the web app was creating dataset versions w/ invalid data and `dpm build-package` was erroneously appearing to succeed: it built packages and reported success. It was able to deserialize API responses into Rust types because serde was deserializing every field into the `StringField` variant, since every field lacked `type` but the data could still be (and was) …
> fix: Expect string fields to always have `type`

- src/command/update.rs
- src/descriptor/table_schema.rs
- Report on PK differences between the 'base' dataset version and the 'next' version staged in memory during `dpm update`
When I was working on `dpm update` recently I'd initially overlooked the fact that when the 'next' version is derived from the `GET /sources/{}/metadata` response it will be lacking primary key info, which would cause the diffing during `dpm update` to say "Hey, the base version and the next version are different" (i.e., `!=`). Further, when it came down to precisely telling the user _what_ differed, we wouldn't report anything meaningful. This fixes that 'the output is meaningless' problem.
In main + temporarily commenting out the 'infer the PKs from the base version' here: https://github.com/patch-tech/dpm/blob/4ef6309309ba2f86e33a3376b38b7fe7bb459fec/src/command/upda …
> feat(update): Identify and report PK differences

- src/api.rs
- src/command/build_package.rs
- src/command/package.rs
- Support arbitrary JSON in `patch_state_data`
See https://patch-tech.slack.com/archives/C04Q0A2TFEV/p1700092912079839?thread_ts=1700002565.919409&cid=C04Q0A2TFEV
Ideally we get the output more concise, but this at least unbreaks `dpm package list` for now.
In my account right now,
```
% cargo run -- package list
┌───────────────────────────────┬────────────────┬──────────────────┬─────────────────────────────────────────────────────────────────────────────────────────┐
│ Name                          ┆ Version        ┆ Performance mode ┆ State                                                                                   │
╞═══════════════════════════════╪════════════════╪══════════════════╪═════════════════════════════════════════════════════════════════════════════════════════╡
│ …
```
> fix(package list): Support JSON state data

- CHANGELOG.md
- src/codegen/generator.rs
- src/command.rs
- src/command/build_package.rs
- src/command/init.rs
- src/command/publish.rs
- src/command/source.rs
- src/descriptor/dataset.rs
- tests/integration_test/target_tester.rs
- Give helpful message when `dpm init` completes
- In docs, rename "descriptor" references to "spec"
- Convert BigQuery's positional `dataset` argument to a named arg `--dataset <NAME>`
Creating a default-named spec (dataset.json),
```
% dpm init -s second-bq-source -n pk-diff-test-fresh
> Select a table to add to dataset: microtable1
> Select the fields that make up the table's primary key name
wrote descriptor: dataset.json
Next, build a draft data package to validate your dataset:
$ dpm build-package csharp
$ dpm build-package nodejs
$ dpm build-package python
Or jump straight to publishing it:
$ dpm publish
Publishing is the first step to making the dataset accessible to others. Once
published, authorized users may query the dataset via GraphQL, or build data
packages to query it:
$ …
```
> feat(init): Give helpful post-init message, execute user-facing rename of descriptor -> spec

- Cargo.lock
- Cargo.toml
- src/command/snowflake.rs
- src/command/source.rs
- Upgrade regress dep
- Support more user-friendly `--account {org}.{account}` format when creating Snowflake sources
Failure:
```
% cargo run -- source create snowflake -n testing-easier-identifier --account ASDF --user redacted --password redacted --database redacted
error creating source: Invalid account identifers given. Provide account identifiers either via `--account ${ORG_NAME}.${ACCOUNT_NAME}, or via `--organization ${ORG_NAME} --account ${ACCOUNT_NAME}`.
```
Success:
```
% cargo run -- source create snowflake -n testing-easier-identifier --account ABC123.DEF456 --user redacted --password redacted --database redacted
Source created
```
&& verifying the expected values were persisted:
```
dpm=> select source_parameters->'organization', source_parameters->'account' from source …
```
> feat(source create snowflake): Support format `--account {org}.{account}`

- static/nodejs/src/backends/dpm_agent/dpm_agent_client.ts
- static/nodejs/test/dpm_query_builder.test.ts
- static/nodejs/test/field_expr.test.ts
- Include all order-by expressions that are not present in the
selection set when computing the group-by clause.
> fix(pat-5034): include order-by expressions when computing the group-by clause

- static/python/src/backends/dpm_agent/dpm_agent_client.py
- static/python/src/backends/factory.py
- static/python/src/field_expr.py
- static/python/src/test/dpm_query_builder_test.py
- Python codegen: include order-by when computing group-by expressions.
> fix(pat-5034): python - include order-by when computing group-by

- CHANGELOG.md
- static/csharp/Dpm/DpmAgentQueryFactory.cs
- static/csharp/DpmTest/TestQueryFormulation.cs
- Include order-by expressions when computing group-by clause.
> fix(pat-5034): c# - include order-by when computing group-by
