patch-tech/dpm

README.md
- Add Homebrew instructions
- Give a better link to `tonic` dependency instructions
=> docs(README): Add Homebrew instructions

Cargo.lock, Cargo.toml, src/github.rs
`dpm login` now copies github code to clipboard, restoring clipboard contents on error or success of login
=> feat(pat-3831): copy gh code to clipboard

src/codegen/nodejs.rs, src/codegen/python.rs, static/nodejs/src/field.ts, static/nodejs/test/field.test.ts, static/python/src/field.py, static/python/src/test/field_expr_test.py, static/python/src/test/field_test.py
- Adds `TimeField` class to `nodeJS` and `Python`.
=> feat(pat-4115): support TimeField

src/codegen/csharp.rs, static/csharp/Dpm/AggregateFieldExpr.cs, static/csharp/Dpm/BooleanFieldExpr.cs, static/csharp/Dpm/DateField.cs, static/csharp/Dpm/DateTimeField.cs, static/csharp/Dpm/DerivedField.cs, static/csharp/Dpm/Field.cs, static/csharp/Dpm/FieldExpr.cs, static/csharp/Dpm/LiteralField.cs, static/csharp/Dpm/Operator.cs, static/csharp/Dpm/Scalar.cs, static/csharp/Dpm/StringField.cs, static/csharp/Dpm/Table.cs, static/csharp/Dpm/UnaryBooleanFieldExpr.cs, static/nodejs/src/table.ts
- Add various class definitions for fiield expressions, field types, and Table class.
=> feat(pat-4053): complete static code classes

src/codegen/csharp.rs
- Improve table codegen so each field can be accessed as its derived type  (e.g. `StringField`) instead of base class `FieldExpr`.
- This allows these fields to be used correctly during query building, e.g., in a `Filter`, the field `Field<int> Age` can be correctly used in a clause `Age > 10`.
- Generated data package, build it successfully, pack-ed it and used it to define and execute queries.
=> feat(pat-4053): improve table codegen to allow access to each field as its derived type

CHANGELOG.md, src/codegen/csharp.rs, static/csharp/Dpm/AggregateFieldExpr.cs, static/csharp/Dpm/DateField.cs, static/csharp/Dpm/DateTimeField.cs, static/csharp/Dpm/Field.cs, static/csharp/Dpm/FieldExpr.cs, static/csharp/Dpm/LiteralField.cs, static/csharp/Dpm/Table.cs, static/csharp/Dpm/TimeField.cs, static/csharp/Dpm/UnaryBooleanFieldExpr.cs, static/nodejs/src/field.ts, static/python/src/field.py
- Add `TimeField` class to static C#
- Add missing boolean ops to supported temporal field classes.
TBD
=> feat(pat-4140): Add TimeField to C#; add missing boolean ops

CHANGELOG.md, src/codegen/csharp.rs, static/csharp/Dpm/Dpm.csproj, static/csharp/Dpm/Table.cs
- Support returning a dynamic [type](https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/interop/using-type-dynamic) for query results, so the caller does not have to define a query result item type.
- Ensure that we call the asynchronous `ExecuteQuery` RPC.
- Define and execute query using generated package:
```c#
var age = FactsAppEngagement.Fields.Age;
var appName = FactsAppEngagement.Fields.Appname;
var screenDuration = FactsAppEngagement.Fields.Screenonduration;
var query = FactsAppEngagement
.Select(age, appName, screenDuration.Sum().As("totalScreenTime"), screenDuration.Max().As("screenDurationMax"))
.Filter(age < 50 & appName.Like("%walmart%"))
.OrderBy((screenDuration.Max(), Direction.DESC))
.Limit(10);
var compiledQuery = query.Compile();
Console.WriteLine($"compiled …
```
=> feat(pat-4176): return dynamic query result; use async execute query

static/csharp/Dpm/Field.cs, static/csharp/DpmTest/UnitTest1.cs
- Fix bug that did not alias fields correctly.
- Updated unit test to assert alias.
=> fix(pat-4258): field aliasing bug

CHANGELOG.md, Cargo.lock, Cargo.toml
- Bump up version to 0.2.0
- Update CHANGELOG
=> feat(pat-4281): release dpm v0.2.0

src/codegen/csharp.rs, src/codegen/nodejs.rs, src/codegen/python.rs
- Update generator impls for all targets to incorporate a `Prerelease` component (assumed to be `draft.N`, if present) into the root dirs and package instance versions
=> feat(build-package): Include draft in roots and manifest versions

CHANGELOG.md, src/api.rs, src/command/source.rs
- Add `--staging-database <NAME>` optional argument when creating a Snowflake source
=> feat(source create): Support --staging-database for Snowflake

src/command.rs
- Add information to `dpm update`'s docs
Fixes https://linear.app/patch-tech/issue/PAT-4377/dpm-update-improve-docstring
=> docs(update): Elaborate on how it functions

CHANGELOG.md, Cargo.lock, Cargo.toml
- Make normal release changes for 0.4.0
- Sort changelog entries in reverse-chronological order (more common, usable)
=> chore(release): 0.4.0

src/codegen/nodejs.rs, static/nodejs/package-lock.json, static/nodejs/package.json, tests/integration_test/nodejs.rs, tests/nodejs/package-lock.json, tests/nodejs/package.json
To reproduce this branch:
```
cd static/nodejs/
npm i @grpc/grpc-js@latest @grpc/proto-loader@latest
```
=> chore(static Node.js tests): Upgrade deps

src/codegen/python.rs, static/python/poetry.lock, static/python/pyproject.toml, static/python/src/field.py, static/python/src/table.py, static/python/src/test/field_test.py
- Defines the `in_past` relative time check as `(lower <= <field> <= upper)`, where `lower, upper` are time bounds computed w.r.t. current time.
=> feat(pat-3355): python - express in_past as check of computed range

CHANGELOG.md, src/codegen/csharp.rs, src/codegen/nodejs.rs, src/codegen/python.rs, static/csharp/Dpm/DateField.cs, static/csharp/Dpm/DateTimeField.cs, static/csharp/Dpm/Operator.cs, static/csharp/Dpm/TimeField.cs, static/csharp/DpmTest/TestDateUtils.cs, static/csharp/DpmTest/TestQueryFormulation.cs, static/python/src/field.py, static/python/src/test/field_test.py, tests/integration_test/nodejs.rs, tests/integration_test/python.rs, tests/nodejs/package-lock.json, tests/nodejs/package.json
- Defines the `InPast` relative time check as `(lower <= <field> <= upper)`, where `lower, upper` are time bounds computed w.r.t. current time.
-  Added unit tests.
=> feat(pat-3355): C# - define InPast in terms of range comparison

CHANGELOG.md, src/api.rs, src/command/build_package.rs, src/command/init.rs, src/command/publish.rs, src/descriptor.rs, src/descriptor/data_package.rs
- Support new `accelerated` boolean at the top level of descriptors
=> feat(publish): Support `accelerated` in descriptor

CHANGELOG.md, Cargo.lock, Cargo.toml, src/api.rs, src/codegen/csharp.rs, src/codegen/nodejs.rs, src/codegen/python.rs, src/command.rs, src/command/package.rs, src/command/publish.rs
- Add `package list` command
It outputs as a table, `ORDER BY package name ASC, package version DESC`.
Output for me:
```
% cargo run -- package list
Compiling dpm v0.4.0 (/Users/spencer/code/dpm)
Finished dev [unoptimized + debuginfo] target(s) in 6.27s
Running `target/debug/dpm package list`
┌───────────────────────────────┬────────────────┬──────────────────┬───────────────────────┐
│ Name                          ┆ Version        ┆ Performance mode ┆ State                 │
╞═══════════════════════════════╪════════════════╪══════════════════╪═══════════════════════╡
│ Snowflake Demo Package        ┆ 0.1.0          ┆ Direct           ┆ n/a                   │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ Snowflake Demo Package (fast) ┆ …
```
=> feat(package list): Add command

src/github.rs
- Support situations without clipboard support, or situations where the current clipboard contents aren't strings that can be saved/restored
When I have an image on my clipboard on macOS:
```
Copy the following login code: AD3B-1CF1
Enter it at this URL: https://github.com/login/device
Session file written to: /Users/spencer/Library/Application Support/tech.patch.dpm/session.json
You are now logged in.
```
This leaves it to the user whether they want to use their clipboard (and in so doing, clobber the non-string content currently on it).
=> fix: Support `login` in variety of less-than-ideal clipboard situations

src/command/init.rs, src/command/snowflake.rs, src/command/update.rs
Identifying tables by the pair (schema, table) helps to unambiguously identify them when calling `snowflake::describe`.
Unfortunately, this PR ended up not being that beneficial, since upstack PRs rework this code. Upstack of this,
- BigQuery introspection will debut using the `GET api.dpm.sh/sources/{}/metadata` endpoint
- Snowflake introspection will be updated to use the same endpoint, rather than using agent.dpm.sh. That update brings with it a logical change: the refinements that the user may supply via CLI (`--table <NAME>` or `--schema <NAME>`) are applied _post hoc_ to the `Vec<DataResource>` obtained from api.dpm.sh, rather than being used as _input_ into the introspection operation to reduce the amount of work done and data returned.
I'm considering ripping out the 'refinements' …
=> refactor(snowflake): Store schema with table when describing Snowflake

static/python/src/backends/dpm_agent/dpm_agent_client.py, static/python/src/field.py, static/python/src/test/field_test.py
- Added ArrayField class.
- Updated agent client to handle `hasAny, hasAll`.
- Added unit tests
=> feat(pat-4832): support ArrayField in python

CHANGELOG.md, static/csharp/Dpm/DateField.cs, static/csharp/Dpm/DateTimeField.cs, static/csharp/Dpm/DerivedField.cs, static/csharp/Dpm/Operator.cs, static/csharp/DpmTest/TestQueryFormulation.cs
Add more temporal projection operators to DateField, and DateTimeField.
- Day of week.
- Week.
- Date.
- Time.
=> feat(pat-4159): support more temporal projections in csharp

DEVELOPMENT.md, tests/integration_test/target_tester.rs
- Add logs during integration tests to indicate attempts and failures at locating test Snowflake config
- Add copy to DEVELOPMENT.md to further orient folks
In main, with invalid env vars and `sops` not installed:
```
% SNOWSQL_ACCOUNT=abc SNOWSQL_account=asdf SNOWSQL_DATABASE=def SNOWSQL_USER=123 SNOWSQL_PWD=456 cargo test --test integration_test
...
---- test_nodejs stdout ----
thread 'test_nodejs' panicked at tests/integration_test/target_tester.rs:25:31:
Failed to execute command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
...
```
In this branch,
```
% SNOWSQL_ACCOUNT=abc SNOWSQL_account=asdf SNOWSQL_DATABASE=def SNOWSQL_USER=123 SNOWSQL_PWD=456 cargo test --test integration_test …
```
=> test: Clarify Snowflake config discovery
